### ISSUE TITLE
Use same version numbering as deno AKA deno-lambda 1.0

### ISSUE THREAD

**Issue by hayd** [hayd/deno-lambda#20]
Requires:

- [x] better typing #18 
- [x] publish to SAR
- [x] support lockfiles #24
- [x] support importmap, config, other flags??
- [ ] decide if should have all permissions? i.e. -A
- [x] missing identity and clientContext on Context #25
- [x] include SAM example https://github.com/brianleroux/sam-example-deno
- [x] update serverless example to use SAR
- [x] reference ARC/other projects **(happy to add others if commented here)**
- [x] cleanup README (move the many images to sep documentation?).

anything else?

---

- [ ] Change QUICK-START to use the SAR app (deploy then look up ARN from Output)
- [x] Add example of line number and date from DENO_PREFIX in README.
- [x] Add LicenseInfo=MIT to SAR app's layer (also description etc?)
- [x] Propagate the tracing header
- [x] add hello-world SAR application (is there such a thing as user-published "blueprint"?)
- [x] console.log multiple lines to CW (#40, this is non-trivial due to rate-limiting)
- [x] settle on console.log format #44 
- [x] use bin/deno rather than amz-deno (amend PATH=/usr/local/bin:/usr/bin/:/bin:/opt/bin and LD_LIBRARY_PATH=/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib in tests to match lambda), this will mean `deno` is in PATH. #45
- [x] become "verified" on SAR

**Comment by hayd** [comment]
This is basically done.

**Comment by hayd** [comment]
Now this is ready! Pending some more feedback...

**Comment by hayd** [comment]
I'm still waiting for verified status on aws SAR (they said it would take "a few days" over a week ago, I've followed up 🤷‍♂️) then I'll likely close this out.

I might add an example for DENO_PREFIX to include date and file/ line number. ...can't really think of much else.

**Comment by hayd** [comment]
Released! 🏅
